command = /usr/bin/zsh -l

quit-after-last-window-closed = false

font-family = JetBrainsMono Nerd Font
font-size = 12
font-feature = liga
font-feature = calt

window-padding-x = 15
window-padding-y = 15
window-padding-balance = true
background-opacity = 0.9
window-decoration = auto
gtk-titlebar = false

desktop-notifications = false

copy-on-select = true

cursor-color = #ffffff
cursor-text = #1A1A1A

background = #1A1A1A
foreground = #d4d4d4

palette = 0=#1A1A1A
palette = 1=#FA7584
palette = 2=#79B8FF
palette = 3=#FFAB70
palette = 4=#B392F1
palette = 5=#E394DC
palette = 6=#79B8FF
palette = 7=#BBBBBB

palette = 8=#5C5C5C
palette = 9=#FF9CAA
palette = 10=#A3D0FF
palette = 11=#FFC9A3
palette = 12=#CFB8FF
palette = 13=#F3B8EC
palette = 14=#A3D0FF
palette = 15=#F8F8F8

keybind = ctrl+shift+c=copy_to_clipboard
keybind = ctrl+shift+v=paste_from_clipboard
keybind = shift+enter=text:\x1b\r
keybind = ctrl+tab=text:\x1b[9;5u
keybind = ctrl+shift+tab=text:\x1b[9;6u
keybind = ctrl+enter=unbind
