"$schema" = 'https://starship.rs/config-schema.json'

format = '$directory$git_branch$character'

[directory]
style = "bold #dddddd"

[git_branch]
format = '[$symbol $branch]($style) '
style = "bold #888888"
symbol = ""

[character]
success_symbol = "[❯](bold #dddddd)"
error_symbol = "[❯](bold #cc6666)"
