# Mudar prefix de C-b para C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Dividir horizontalmente (um acima do outro) com prefix + h
unbind '"'
bind h split-window -v

# Dividir verticalmente (lado a lado) com prefix + v
unbind %
bind v split-window -h

# Navegar entre painéis com prefix + teclas de seta
bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D

# Recarregar configuração com prefix + r
bind r source-file ~/.tmux.conf \; display "Config recarregada!"

# prefix + d → mata a sessão e fecha o terminal
bind d kill-session
# prefix + D → detach (sessão continua viva)
bind D detach-client

# Melhorar cores
set -g default-terminal "screen-256color"
set -g extended-keys on
set -as terminal-features ",*:extkeys"

set -g allow-passthrough on

# Aumentar histórico de scroll
set -g history-limit 10000

# Renumerar janelas automaticamente quando uma é fechada
set -g renumber-windows on

# Habilitar mouse
set -g mouse on

# Reduzir tempo de escape
set -sg escape-time 0

# Detectar mudanças de foco (pro nvim recarregar arquivos editados por fora)
set -g focus-events on

# Cor de seleção
set -g mode-style "bg=#3a3a3a,fg=#ffffff"

# Bordas dos painéis
set -g pane-border-style "fg=#3a3a3a"
set -g pane-active-border-style "fg=#888888"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @tmux-dotbar-bg "default"
set -g @tmux-dotbar-fg "#cccccc"
set -g @tmux-dotbar-fg-current "#ffffff"
set -g @tmux-dotbar-fg-session "#dddddd"
set -g @tmux-dotbar-fg-prefix "#ffffff"
set -g @tmux-dotbar-right "true"
set -g @tmux-dotbar-position "top"
set -g @tmux-dotbar-window-status-format " #W "

set -g status 2
set -g status-format[1] "#[fg=#4d4d4d]────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────"

run '~/.tmux/plugins/tpm/tpm' 
